### ISSUE TITLE
Climate IP 6.3 issue - Creating socket failed!

### ISSUE THREAD

**Issue by Ross65** [atxbyea/samsungrac#116]
Hello, 
after updating to version 6.3 the following error is recurring. Rolling back to 6.2 solve the issue.
---
2024-10-20 10:41:44.021 ERROR (SyncWorker_34) [custom_components.climate_ip] Creating socket failed!
2024-10-20 10:41:55.923 ERROR (SyncWorker_14) [custom_components.climate_ip] Error: Traceback (most recent call last):
  File "/config/custom_components/climate_ip/samsung_2878.py", line 283, in create_connection
    sslSocket.connect((cfg.host, cfg.port))
  File "/usr/local/lib/python3.12/ssl.py", line 1353, in connect
    self._real_connect(addr, False)
  File "/usr/local/lib/python3.12/ssl.py", line 1340, in _real_connect
    super().connect(addr)
OSError: [Errno 113] Host is unreachable

**Comment by atxbyea** [comment]
Host is unreachable would usually mean that there is no network connection to the device.

**Comment by samuelecarpene** [comment]
Please give us some information about your configurations.
