### ISSUE TITLE
Not arrive to make it work with AR12HSFSAWKN

### ISSUE THREAD

**Issue by xducu** [atxbyea/samsungrac#120]
Hello,
I tried to implement Climate_Ip ver. 7.0 for an AR12HSFSAWKN in HA and unfortunately I couldn't get it to work. I received the following error message in the log.
Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f753f8cd0>,) inside the event loop by custom integration 'climate_ip' at custom_components/climate_ip/samsung_2878.py, line 267: sslContext.load_verify_locations(cafile=cfg.cert) (offender: /config/custom_components/climate_ip/samsung_2878.py, line 267: sslContext.load_verify_locations(cafile=cfg.cert)), ...
I running HA OS 13.2 Core 2024.11.3 Frontend 20241106.2 on a  Pi 4.

Thanks in advance for some help.

Best regards,
Ducu

**Comment by xducu** [comment]
Yes I tried also with cert: '' in the configuration.yaml but still without succes, the AC don't want to start... 

My configuration is:

climate:
    - platform: climate_ip
      name: Aircon Living
      device_id: aircon_living1
      config_file: 'samsung_2878.yaml'
      ip_address: 192.168.30.97
      token: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx (edited)
      cert: ''   #set as '' to skip certificate verification
      mac: F8-04-2E-27-C0-E2
      poll: True
      debug: True

hereafter the error log:

Logger: custom_components.climate_ip
Source: custom_components/climate_ip/samsung_2878.py:289
integration: Climate IP ([documentation](https://github.com/atxbyea/samsungrac), [issues](https://github.com/atxbyea/samsungrac/issues))
First occurred: 8:18:25 PM (58 occurrences)
Last logged: 8:24:13 PM

Error: Traceback (most recent call last): File "/config/custom_components/climate_ip/samsung_2878.py", line 283, in create_connection sslSocket.connect((cfg.host, cfg.port)) File "/usr/local/lib/python3.12/ssl.py", line 1353, in connect self._real_connect(addr, False) File "/usr/local/lib/python3.12/ssl.py", line 1344, in _real_connect self.do_handshake() File "/usr/local/lib/python3.12/ssl.py", line 1320, in do_handshake self._sslobj.do_handshake() ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1000)
