### ISSUE TITLE
climate_ip stopped working

### ISSUE THREAD

**Issue by rgogada** [atxbyea/samsungrac#34]
I have been using this component for a while without any issues. but something broke it recently. either 2021.9 or a recent hacs update. not really sure. I could see the below in the log file. please let me know if you need anything else for investigation.

File "/config/custom_components/climate_ip/climate.py", line 261, in update
    self.rac.update_state()
  File "/config/custom_components/climate_ip/controller_yaml.py", line 206, in update_state
    self._state_getter.update_state(self._state_getter.value, debug)
  File "/config/custom_components/climate_ip/properties.py", line 257, in update_state
    device_state = self.get_connection(None).execute(
  File "/config/custom_components/climate_ip/samsung_2878.py", line 308, in execute
    self.send_socket_command(message, 1)
  File "/config/custom_components/climate_ip/samsung_2878.py", line 219, in send_socket_command
    sslSocket = self.socket
  File "/config/custom_components/climate_ip/samsung_2878.py", line 281, in socket
    self.create_connection()
  File "/config/custom_components/climate_ip/samsung_2878.py", line 270, in create_connection
    sslSocket.connect((cfg.host, cfg.port))
  File "/usr/local/lib/python3.9/ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "/usr/local/lib/python3.9/ssl.py", line 1333, in _real_connect
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()

**Comment by rgogada** [comment]
went back to 3.5.1 and all is well.
BTW I am using 2878 yaml.

**Comment by d00wirre** [comment]
Also have the same issue.
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129) seems to be the error if i understand correctly

Config:
`climate:
  - platform: climate_ip
    config_file: "samsung_2878.yaml"
    ip_address: "10.0.0.61"
    token: ""
    cert: '' #set as '' to skip certificate verification
    mac: "78:25:AD:12:1E:8D"
    poll: True
    debug: True
    name: "Livingroom AC"`


Log:
`2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] climate_ip: async setup platform
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Loading configuration file: /config/custom_components/climate_ip/samsung_2878.yaml
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] ip_address: 10.0.0.61
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] token: 
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Validate properties: False (False)
2021-09-29 20:37:04 WARNING (MainThread) [custom_components.climate_ip.climate] WARNING: 'cert' parameter is empty, skipping certificate validation
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Configuration, host: 10.0.0.61:2878
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Configuration, token: 
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Configuration, duid: 7825AD121E8D
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Configuration, cert: None
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Updating state...
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Updating getter...
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Executing params: {'duid': '7825AD121E8D', 'token': '', 'host': '10.0.0.61', 'connection_template': '<Request Type="AuthToken"><User Token="{{token}}" /></Request>', 'power_template': '{% if value != none %}{% for key, value in device_state.items() %}{% if key == "AC_FUN_POWER" %}{% if value == "Off" %}<Request Type="DeviceControl"><Control CommandID="AC_FUN_POWER" DUID="{{duid}}"><Attr ID="AC_FUN_POWER" Value="On" /></Control></Request>{% endif %}{% endif %}{% endfor %}{% endif %}', 'value': None, 'device_state': 'unknown'}
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Checking power on template: <Template memory:7fb8b16ee850>
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Power on template found, rendering
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Power on message:
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Executing command: <Request Type="DeviceState" DUID="7825AD121E8D"></Request>
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Getting socket connection
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Connection invalid, creating!
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Creating ssl context
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Setting up ciphers
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Setting up verify mode
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Cert is empty, skipping verification
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Wrapping socket
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Socket wrapped: True
2021-09-29 20:37:04 INFO (MainThread) [custom_components.climate_ip.climate] Connecting with 10.0.0.61:2878
2021-09-29 20:37:05 INFO (MainThread) [custom_components.climate_ip.climate] Sending command failed
2021-09-29 20:37:05 INFO (MainThread) [custom_components.climate_ip.climate] Traceback (most recent call last):
File "/config/custom_components/climate_ip/samsung_2878.py", line 219, in send_socket_command
sslSocket = self.socket
File "/config/custom_components/climate_ip/samsung_2878.py", line 281, in socket
self.create_connection()
File "/config/custom_components/climate_ip/samsung_2878.py", line 270, in create_connection
sslSocket.connect((cfg.host, cfg.port))
File "/usr/local/lib/python3.9/ssl.py", line 1342, in connect
self._real_connect(addr, False)
File "/usr/local/lib/python3.9/ssl.py", line 1333, in _real_connect
self.do_handshake()
File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)`

**Comment by d00wirre** [comment]
Found the comments on commit be39a72 and the solution there, rolling back fixes this bug.

**Comment by atxbyea** [comment]
fixed in https://github.com/atxbyea/samsungrac/pull/38 thanks @d00wirre @giig982 @knutmyr
