### ISSUE TITLE
Error adding entities for domain climate with platform climate_ip

### ISSUE THREAD

**Issue by rgogada** [atxbyea/samsungrac#49]
climate_ip not working after recent updates
HA: 2022.7.5
climate_ip: 4.2

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:220
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 9:08:08 AM (2 occurrences)
Last logged: 9:08:08 AM

Error adding entities for domain climate with platform climate_ip
Error while setting up climate_ip platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: '' is not a valid HVACMode

**Comment by rgogada** [comment]
work around: reverting back to version 4.1

**Comment by rauljerico** [comment]
Same problem here.

**Comment by andriuskr** [comment]
Downgrade to 4.1 solves the issue

**Comment by d00wirre** [comment]
Have the same issue.

```console
2022-09-16 22:18:44.811 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.climate_ip.climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/climate_ip/__init__.py", line 3, in <module>
from .connection_request import ConnectionRequest, ConnectionRequestPrint
File "/config/custom_components/climate_ip/connection_request.py", line 1
\\import concurrent.futures
^
SyntaxError: unexpected character after line continuation character
2022-09-16 22:18:44.813 ERROR (MainThread) [homeassistant.config] Platform error: climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/climate_ip/__init__.py", line 3, in <module>
from .connection_request import ConnectionRequest, ConnectionRequestPrint
File "/config/custom_components/climate_ip/connection_request.py", line 1
\\import concurrent.futures
^
SyntaxError: unexpected character after line continuation character
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config.py", line 878, in async_process_component_config
platform = p_integration.get_platform(domain)
File "/usr/src/homeassistant/homeassistant/loader.py", line 690, in get_platform
raise ImportError(
ImportError: Exception importing custom_components.climate_ip.climate

**Comment by AI-ien** [comment]
For me downgrading to 4.1 or even to 4.0 didn't help.
