### ISSUE TITLE
Creating socket failed!

### ISSUE THREAD

**Issue by AI-ien** [atxbyea/samsungrac#53]
v4.2
HA docker version

Logger: custom_components.climate_ip.climate
Source: custom_components/climate_ip/samsung_2878.py:308
Creating socket failed!

Which is line `self.send_socket_command(message, 1)`

This is followed by next error Error adding entities for domain climate with platform climate_ip:

```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:245
Integration: Climate (documentation, issues)
First occurred: 10:48:49 PM (1 occurrences)
Last logged: 10:48:49 PM

Error adding entities for domain climate with platform climate_ip
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 245, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: '' is not a valid HVACMode
```

**Comment by AI-ien** [comment]
This was driving me mad. I even re-installed entire HA and moved from docker version to OS to no avail. In the end solution was simple, I had to restart AC unit by turning it off and on. Who knew.
Issue can be closed.
