### ISSUE TITLE
Release 4.2 breaks Samsung 2878

### ISSUE THREAD

**Issue by thomasja27** [atxbyea/samsungrac#56]
Get this error with my 2878 samsung AC, on Release 4.2.
Rolled back to Release 4.1. Then everything works fine.

Logger: homeassistant
Source: components/climate/__init__.py:245
First occurred: 11:21:20 (21 occurrences)
Last logged: 11:31:22

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 813, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 245, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: '' is not a valid HVACMode

**Comment by deece** [comment]
I get the same on master, & can confirm that 4.1 works

**Comment by deece** [comment]
#52 is related

**Comment by bositman** [comment]
Not sure if #52 is related, i have the same issue with Samsung 2878, running latest  HA 2023.1.7 with 4.1 and it's working fine, while at that issue people can't get it to work in latest HA versions. As OP, 4.2 breaks it for me and 4.1 works

**Comment by Nick398** [comment]
This was fixed with version 5.1

**Comment by bositman** [comment]
Can confirm 5.1 works fine with Samsung 2878
