### ISSUE TITLE
Latest HA updates breaks ClimateIP

### ISSUE THREAD

**Issue by buzurk26** [atxbyea/samsungrac#58]
Hi

Samsung HVAC using climate IP for some time working well, latest home assistant update looks to have broken it, tried 4.1 as others have suggested, no dice

Logs

`Error adding entities for domain climate with platform climate_ip
Error while setting up climate_ip platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 804, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 245, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: '' is not a valid HVACMode`

**Comment by brunofosi** [comment]
can confirm. i'm having the same issue

**Comment by repvik** [comment]
Same issue on a new install.

**Comment by ismaelrivas** [comment]
i'm having the same issue

**Comment by atxbyea** [comment]
should be fixed in 4.3
