### ISSUE TITLE
HAS 2023.6.1 - Broken

### ISSUE THREAD

**Issue by buzurk26** [atxbyea/samsungrac#71]
I upgraded HAS today and my Samsung AC has dropped out, it couldn't load so i took a gamble and upgraded the addon to the latest 5.1 (was on 4.0)

Up until now, I have deliberately stuck with v4.0 of this addon as it was the only one that wanted to work but when it didn't load after HAS upgrade i went to the latest to see if it would fix it.

Since going to 5.1 the dial is back, but no temps and control is not working, i can't see any errors in HA logs either.
![image](https://github.com/atxbyea/samsungrac/assets/39994663/b1474d87-4b21-4d71-941e-f51f2eb38c51)

Anyone experiencing the same?

Using 2878 on a MIM-H02

EDIT: Starting to see these
![image](https://github.com/atxbyea/samsungrac/assets/39994663/4ee62d2d-7fe4-45b4-a50f-5739ec3fc7a2)
![image](https://github.com/atxbyea/samsungrac/assets/39994663/36da5385-c335-4fa1-b8c5-940952d4796c)

The Unit is responding OK as i can still use it via the old Samsung app

**Comment by lucadjc** [comment]
Ciao all,
I'm still debugging it but it seems that with the new Hassio version, the openssl version has been upgraded and the TLSv1 setting is not working correctly, below the log


2023-06-11 16:06:13.149 INFO (MainThread) [custom_components.climate_ip.climate] **OpenSSL 3.1.0 14 Mar 2023**
2023-06-11 16:06:13.149 INFO (MainThread) [custom_components.climate_ip.climate] Creating ssl context
2023-06-11 16:06:13.154 INFO (MainThread) [custom_components.climate_ip.climate] Setting up ciphers
2023-06-11 16:06:13.155 INFO (MainThread) [custom_components.climate_ip.climate] Setting up verify mode
2023-06-11 16:06:13.155 INFO (MainThread) [custom_components.climate_ip.climate] Certificate Required: 2
2023-06-11 16:06:13.155 INFO (MainThread) [custom_components.climate_ip.climate] Verify mode: 0
2023-06-11 16:06:13.155 INFO (MainThread) [custom_components.climate_ip.climate] Cert is empty, skipping verification
2023-06-11 16:06:13.155 INFO (MainThread) [custom_components.climate_ip.climate] Wrapping socket
2023-06-11 16:06:13.156 INFO (MainThread) [custom_components.climate_ip.climate] Socket wrapped: True
2023-06-11 16:06:13.156 INFO (MainThread) [custom_components.climate_ip.climate] Connecting with 192.168.1.XX:2878
2023-06-11 16:06:30.008 INFO (MainThread) [custom_components.climate_ip.climate] Error: Traceback (most recent call last):
File "/config/custom_components/climate_ip/samsung_2878.py", line 283, in create_connection
sslSocket.connect((cfg.host, cfg.port))
File "/usr/local/lib/python3.11/ssl.py", line 1379, in connect
self._real_connect(addr, False)
File "/usr/local/lib/python3.11/ssl.py", line 1370, in _real_connect
self.do_handshake()
File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1002)

**Comment by Nick398** [comment]
I was on Samsungrac 5.1 and it was working well. Running HA Supervised and it has broken upgrading from core_2023.5.4 to 2023_6.1.

I am getting a different erro, though.

```
Logger: homeassistant.components.climate
Source: custom_components/climate_ip_bak/climate.py:285
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 5:46:08 PM (2 occurrences)
Last logged: 5:46:08 PM

Error adding entities for domain climate with platform climate_ip
Error while setting up climate_ip platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 749, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 850, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 656, in _async_write_ha_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/climate_ip_bak/climate.py", line 269, in state_attributes
    attrs.update(super(ClimateIP, self).state_attributes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 297, in state_attributes
    self.current_temperature,
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/climate_ip_bak/climate.py", line 285, in current_temperature
    return (self.rac.get_property(ATTR_CURRENT_TEMPERATURE) - 55)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by menzy81** [comment]
I am also getting the same errors after upgrading to 2023.6.2


`Logger: homeassistant.components.climate
Source: custom_components/climate_ip/climate.py:289
Integration: Climate (documentation, issues)
First occurred: 12:28:25 AM (2 occurrences)
Last logged: 12:28:25 AM

Error adding entities for domain climate with platform climate_ip
Error while setting up climate_ip platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 749, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 850, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 656, in _async_write_ha_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/climate_ip/climate.py", line 273, in state_attributes
    attrs.update(super(ClimateIP, self).state_attributes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 297, in state_attributes
    self.current_temperature,
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/climate_ip/climate.py", line 289, in current_temperature
    return (self.rac.get_property(ATTR_CURRENT_TEMPERATURE)-55) #-55 for correct offset
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
`

**Comment by Nick398** [comment]
Agree with @lucadjc , seems to be related to the change of Python 3.10 to 3.11 and the ssl library

```
2023-06-18 17:12:59.653 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Getting socket connection
2023-06-18 17:12:59.653 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Connection invalid, creating!
2023-06-18 17:12:59.653 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Creating ssl context
2023-06-18 17:12:59.655 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Setting up ciphers
2023-06-18 17:12:59.656 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Setting up verify mode
2023-06-18 17:12:59.656 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Cert is empty, skipping verification
2023-06-18 17:12:59.656 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Wrapping socket
2023-06-18 17:12:59.656 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Socket wrapped: True
2023-06-18 17:12:59.656 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Connecting with 192.168.xxx.xxx:2878
2023-06-18 17:12:59.664 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Sending command failed
2023-06-18 17:12:59.666 INFO (SyncWorker_7) [custom_components.climate_ip.climate] Traceback (most recent call last):
File "/config/custom_components/climate_ip/samsung_2878.py", line 219, in send_socket_command
sslSocket = self.socket
^^^^^^^^^^^
File "/config/custom_components/climate_ip/samsung_2878.py", line 281, in socket
self.create_connection()
File "/config/custom_components/climate_ip/samsung_2878.py", line 270, in create_connection
sslSocket.connect((cfg.host, cfg.port))
File "/usr/local/lib/python3.11/ssl.py", line 1379, in connect
self._real_connect(addr, False)
File "/usr/local/lib/python3.11/ssl.py", line 1370, in _real_connect
self.do_handshake()
File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL] internal error (_ssl.c:1002)
```

**Comment by lucadjc** [comment]
I’m thinking to move to a container to force old version of python…

**Comment by menzy81** [comment]
Is there any progress on this issue? I am keen to upgrade HA. Happy to provide logs if required or test potential fixes.

**Comment by lucadjc** [comment]
Who is running on a working version, please can share the openssl version?

**Comment by menzy81** [comment]
I am running 2023.6.1 on my dev envirionment which is having the issue & 2023.5.3 on my production environment which is not having the issue. Let me know what command to run & I can post the results.

**Comment by lucadjc** [comment]
> I am running 2023.6.1 on my dev envirionment which is having the issue & 2023.5.3 on my production environment which is not having the issue. Let me know what command to run & I can post the results.

You need to:

- navigate to "homeassistant\custom_components\climate_ip" folder and open samsung_2878.py file. there is the method 
def create_connection(self): add the instruction 
 **self.logger.info(ssl.OPENSSL_VERSION)**

inside the configuration.yaml file, within climate section, assign the attribute     
debug: True
restart Hassio and into the log files you should see the OpenSsl version number

**Comment by menzy81** [comment]
As requested here is the information.

Newer install - not working
HA 2023.6.2
OpenSSL 3.1.1 30 May 2023

Older install - working
HA 2023.5.3
OpenSSL 3.0.8 7 Feb 2023

Let me know if you need anything else. :)

**Comment by lucadjc** [comment]
Perfect, i will investigate doing deep dives

**Comment by lucadjc** [comment]
Thanks to the support to OpenSSL official support, I found the solution
https://github.com/openssl/openssl/issues/21343

Is needed to replace within **samsung_2878.py** file 
the statement
sslContext.set_ciphers("HIGH:!DH:!aNULL")

with
sslContext.set_ciphers("HIGH:!DH:!aNULL:@SECLEVEL=0")
in the couple of hours I'm commit the PR

regards

**Comment by buzurk26** [comment]
That is great news

If we use this one in HACS is that the correct repo to use to get update?
https://github.com/atxbyea/samsungrac

**Comment by lucadjc** [comment]
Yes, this repo is the correct one, just wait for the release from @atxbyea

**Comment by Nick398** [comment]
Legend!

**Comment by Nick398** [comment]
I have downloaded @lucadjc 's fork and it's working fine with HA 2023.7.3. I'll come back to @atxbyea 's version once the code is merged.
You can download his code ([here](https://github.com/lucadjc/samsungrac)) directly in the custom_components/climate_ip folder, restart HA, check that it's working, update HA core to latest.

**Comment by atxbyea** [comment]
thanks @lucadjc
