### ISSUE TITLE
SSL Error: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:3900)

### ISSUE THREAD

**Issue by Domme0506** [atxbyea/samsungrac#72]
`Listening on localhost:8889
/root/server.py:44: DeprecationWarning: ssl.wrap_socket() is deprecated, use SSLContext.wrap_socket()
  server.socket = ssl.wrap_socket(server.socket, certfile='cert.pem', server_side=True)
Traceback (most recent call last):
  File "/root/server.py", line 48, in <module>
    main()
  File "/root/server.py", line 44, in main
    server.socket = ssl.wrap_socket(server.socket, certfile='cert.pem', server_side=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1443, in wrap_socket
    context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:3900)
`

I get this error

**Comment by atxbyea** [comment]
Do you still have this error @Domme0506

**Comment by patrickblau90** [comment]
Hi, unfortunately i have this problem, trying to get my AC token
