### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by Jens-Wymeersch** [atxbyea/samsungrac#81]
I'm getting after every few reboots the following error log. Can you please have a look and see what can be done ?

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/climate_ip/climate.py", line 176, in async_setup_platform
    if dev.service_schema_map:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClimateIP' object has no attribute 'service_schema_map'
```

**Comment by atxbyea** [comment]
Do you still have this error @Jens-Wymeersch  ?

**Comment by alekspere** [comment]
Getting the same error:

```
2025-05-12 09:50:30.466 ERROR (MainThread) [homeassistant.components.climate] Error while setting up climate_ip platform for climate: 'ClimateIP' object has no attribute 'service_schema_map'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/climate_ip/climate.py", line 176, in async_setup_platform
    if dev.service_schema_map:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClimateIP' object has no attribute 'service_schema_map'
```

Using `homeassistant 2025.5` and `samsungrac 7.0`
