### ISSUE TITLE
Stopped working unexpectantly

### ISSUE THREAD

**Issue by menzy81** [atxbyea/samsungrac#93]
No updates were performed in HA, I have had to remove it completely as it was making my HA not respond.

Anyone else experiencing this?

```
Error: Traceback (most recent call last): File "/config/custom_components/climate_ip/samsung_2878.py", line 283, in create_connection sslSocket.connect((cfg.host, cfg.port)) File "/usr/local/lib/python3.12/ssl.py", line 1353, in connect self._real_connect(addr, False) File "/usr/local/lib/python3.12/ssl.py", line 1344, in _real_connect self.do_handshake() File "/usr/local/lib/python3.12/ssl.py", line 1320, in do_handshake self._sslobj.do_handshake() ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)
Error: Traceback (most recent call last): File "/config/custom_components/climate_ip/samsung_2878.py", line 283, in create_connection sslSocket.connect((cfg.host, cfg.port)) File "/usr/local/lib/python3.12/ssl.py", line 1353, in connect self._real_connect(addr, False) File "/usr/local/lib/python3.12/ssl.py", line 1344, in _real_connect self.do_handshake() File "/usr/local/lib/python3.12/ssl.py", line 1320, in do_handshake self._sslobj.do_handshake() ConnectionResetError: [Errno 104] Connection reset by peer
```
```
This error originated from a custom integration.

Logger: custom_components.climate_ip.climate
Source: custom_components/climate_ip/samsung_2878.py:299
integration: climate_ip (documentation, issues)
First occurred: 5:00:00 PM (46 occurrences)
Last logged: 5:07:09 PM

Creating socket failed!
```
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/climate_ip/climate.py:294
integration: climate_ip (documentation, issues)
First occurred: 5:00:25 PM (21 occurrences)
Last logged: 5:07:09 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 963, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1052, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 322, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/climate_ip/climate.py", line 278, in state_attributes
    attrs.update(super(ClimateIP, self).state_attributes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 469, in state_attributes
    hass, self.current_temperature, temperature_unit, precision
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 322, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/climate_ip/climate.py", line 294, in current_temperature
    return (self.rac.get_property(ATTR_CURRENT_TEMPERATURE)-55) #-55 for correct offset
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:865
integration: Climate (documentation, issues)
First occurred: 5:00:05 PM (1 occurrences)
Last logged: 5:00:05 PM

Error adding entity climate.climate_ip_samsungrac for domain climate with platform climate_ip
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 865, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1328, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1052, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 322, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/climate_ip/climate.py", line 278, in state_attributes
    attrs.update(super(ClimateIP, self).state_attributes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 469, in state_attributes
    hass, self.current_temperature, temperature_unit, precision
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 322, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/climate_ip/climate.py", line 294, in current_temperature
    return (self.rac.get_property(ATTR_CURRENT_TEMPERATURE)-55) #-55 for correct offset
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by atxbyea** [comment]
Did you get this working again @menzy81 ?

**Comment by menzy81** [comment]
> Did you get this working again @menzy81 ?

Yes, I ended up replacing my MIMH02 with a new old stock unit.
